Buff magic weapon, enlarge/reduce, and lightning lure (SP 20, 26–27)
JamesMcClung/2d-standard pull request #28
Opened 2024-06-18 19:26 UTC by JamesMcClung

Note that the enlarge/reduce and lightning lure buffs are slightly different from the original spell proposals (which have since been edited so they currently do match)

2024-06-23 04:45 UTC, bwhetherington requested changes
Looks good, barring some missing commas.

2024-06-23 04:45 UTC, bwhetherington commented on spells.yml
> +    **Enlarge.** The target's size doubles in all dimensions, and its weight is multiplied by eight. This growth increases its size by one category—from Medium to Large, for example. If there isn't e
Grammar nit: there should be a comma after "increases by 5 feet".

2024-06-23 04:45 UTC, bwhetherington commented on spells.yml
> +    **Reduce.** The target's size is halved in all dimensions, and its weight is reduced to one-eighth of normal. This reduction decreases its size by one category—from Medium to Small, for example.
Once again, there should be a comma after "(to a minimum of 5 feet)".

2024-06-23 04:45 UTC, bwhetherington commented on spells.yml
> +    You create a lash of lightning energy that strikes at one creature of your choice that you can see within range. The target must succeed on a Strength saving throw or take 1d10 lightning damage a
Comma

2024-06-26 21:26 UTC, JamesMcClung commented
> Looks good, barring some missing commas.

I believe it is actually correct to not have those commas

2024-06-26 21:31 UTC, bwhetherington commented on spells.yml
> +    You create a lash of lightning energy that strikes at one creature of your choice that you can see within range. The target must succeed on a Strength saving throw or take 1d10 lightning damage a
This one does not need a comma, but the others do.

2024-06-26 21:32 UTC, bwhetherington commented
You have independent clauses connected by "and". A comma is necessary there, and this is also the standard followed by the rest of the spells, including the rest of the descriptions of these spells. Look at _enlarge_ as an example:

> The target's size doubles in all dimensions, and its weight is multiplied by eight.

If you have a sentence that goes something like "It <does something> and it <does something else>", then you need a comma before the "and". See [here](https://www.brandeis.edu/writing-program/resources/students/academic/style-grammar/comma-rules.html#:~:text=Use%20commas%20to%20separate%20independent,but%20my%20brother%20prefers%20chocolate.) for more specifics.

2024-06-26 21:45 UTC, JamesMcClung commented
Normally yes, but the presence of the subordinate clause `Until the spell ends` might change that. I'm still looking for an answer online

2024-06-27 01:30 UTC, bwhetherington approved these changes

2024-06-27 01:36 UTC, merged